### ISSUE TITLE
Cannot run fish

### ISSUE THREAD

**Issue by rwols** [percevalw/SublimeTerm#1]
I can't seem to run the fish shell, any ideas?

I get this message (in the view) when I try to open a fish terminal:
```
<W> fish: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
```

**Comment by percevalw** [comment]
Indeed, there seems to be some problems to make the package communicate with fish that it can handle a shell. You can wrap it in bash like this 
```
{
   "command": ["/bin/bash", "-l", "-c", "/usr/local/bin/fish", "-l"]
}
```
and after upgrading the package, it should work ! :)

**Comment by rwols** [comment]
Thanks, this works for now. Ideally, the plugin should probably use `os.environ["SHELL"]`
